name: Deploy PHP/WordPress Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Backup Old Code
        run: |
          # SSH into the server
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'ENDSSH'

            # Change to the application directory
            cd /var/www/wordpress.nanisys.online/wordpress_demo_bsf

            # Create a timestamp for the backup
            backup_timestamp=$(date +"%Y%m%d%H%M%S")

            # Zip the old code and move it to the backup directory
            zip -r "/opt/backups/wordpress_${backup_timestamp}.zip" .

          ENDSSH

      - name: Deploy New code via SSH
        run: |

          # SSH into the server
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'ENDSSH'
            
          # Change to the application directory
          cd /var/www/wordpress.nanisys.online/wordpress_demo_bsf

          # Pull the latest changes from the repository
          git pull origin master

          ENDSSH
